In [1]:
import numpy as np
from termcolor import colored

#Setting up a 6x7 array of zeros to represent the Connect 4 Board (0 = empty, 1 = red, 2 = yellow):
board = np.zeros((6,7))
print(board)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [2]:
#Prints the Connect 4 board
def printboard(board):  #Uses colored in termcolor library to create different colored circles which are the " \u2b24 "
    print('---------------------------')
    for row in board:
        print('|',end='')
        for item in row:
            if (item == 0):
                print(" \u2b24 ", end="")  #Grey circle with new line
            elif (item == 1):
                print(colored(" \u2b24 ",'red'), end="")  #Red circle with new line
            else:
                print(colored(" \u2b24 ",'yellow'), end="")  #Yellow circle with new line
        print('|')
    print('---------------------------')
printboard(board)

---------------------------
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
---------------------------


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [3]:
#Functions to check for any win conditions (4-in-a-row):
def check_verticals(board):
  for column in range(7):
      for row in range(3):
        if (board[row,column] == 1 and board[row+1,column] == 1 and board[row+2,column] == 1 and board[row+3,column] == 1) or (board[row,column] == 2 and board[row+1,column] == 2 and board[row+2,column] == 2 and board[row+3,column] == 2):
          return True

def check_horizontals(board):
  for row in range(6):
    for column in range(4):
      if (board[row,column] == 1 and board[row,column+1] == 1 and board[row,column+2] == 1 and board[row,column+3] == 1) or (board[row,column] == 2 and board[row,column+1] == 2 and board[row,column+2] == 2 and board[row,column+3] == 2):  
        return True

def check_diags_lr(board):
  for column in range(4):
    for row in range(5,2,-1):
      if (board[row,column] == 1 and board[row-1,column+1] == 1 and board[row-2,column+2] == 1 and board[row-3,column+3] == 1) or (board[row,column] == 2 and board[row-1,column+1] == 2 and board[row-2,column+2] == 2 and board[row-3,column+3] == 2): 
        return True

def check_diags_rl(board):
  for column in range(6,2,-1):
    for row in range(5,2,-1):
      if (board[row,column] == 1 and board[row-1,column-1] == 1 and board[row-2,column-2] == 1 and board[row-3,column-3] == 1) or (board[row,column] == 2 and board[row-1,column-1] == 2 and board[row-2,column-2] == 2 and board[row-3,column-3] == 2):
        return True
  
##################################################################################################################################################################################################

def player_won(board):
  won = False
  if check_verticals(board) == True or check_horizontals(board) == True or check_diags_lr(board) == True or check_diags_rl(board) == True:  #Tests if a player has won
    won = True
  return won

def board_filled(board):
  filled = False
  for row in range(6):
    for column in range(7):
      if board[row,column] == 0:
        break
      elif row == 5 and column == 6 and board[row,column] != 0:
        filled = True
        return filled

In [4]:
def get_column(Rturn):  #Gets a column number from the user
  if Rturn:  #Red player chooses
    temp = input("Red player, choose a column to put your piece in (1-7): ")
  else:  #Yellow player chooses
    temp = input("Yellow player, choose a column to put your piece in (1-7): ")
  
  if (temp not in "1234567") or (len(temp) > 1):
    print("Input must be an integer between 1 and 7")
    get_column(Rturn)
  
  column = int(temp) - 1
  return column

def switch_turns(Rturn):
    if Rturn:  #Red player's turn just finished
      Rturn = False
      return Rturn
    else:  #Yellow player's turn just finished
      Rturn = True
      return Rturn

##################################################################################################################################################################################################

#The main gameplay control:
game_over = False
Rturn = True  #The red player goes first

while not game_over:
  printboard(board)

  valid = False  
  while not valid:
    column = get_column(Rturn)  #An index between 0 and 6

    #Putting the piece inside the board
    for row in range(6, 0, -1):  #Iterates from the bottom row to top row (Connect 4 pieces fill vertically upward)
      row -= 1  #Index of row position 
      if (board[row,column] == 1) or (board[row,column] == 2):  #Test if a piece is already there     
        if row == 0:  #The top spot in the column is filled
          print("This column is filled!")
      else:  #There is an available spot in the column
        valid = True
        if Rturn:
          board[row,column] = 1 
        else:
          board[row,column] = 2
        break

  #Tests if the game is over after a player moves:
  if (player_won(board)):
    printboard(board)
    if Rturn:
      print("The red player has won!")
      game_over = True
    else:
      print("The yellow player has won!")
      game_over = True
  elif (board_filled(board)):
    printboard(board)
    print("The board has been filled and it is a tie!")
    game_over = True

  #Switchs turns:  
  Rturn = switch_turns(Rturn)

---------------------------
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
---------------------------
---------------------------
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
---------------------------
---------------------------
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
---------------------------
---------------------------
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
| ⬤  ⬤  ⬤  ⬤  ⬤  ⬤  ⬤ |
---------------------------


ValueError: invalid literal for int() with base 10: ''